services:
  influx:
    image: influxdb:2.7.4
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: cl
      DOCKER_INFLUXDB_INIT_BUCKET: activities
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INfLUX_TOKEN}
  bot:
    build: .
    restart: always
